language: node_js
node_js: node
deploy:
  provider: heroku
  api_key:
    secure: l4/CGvg21Yuxr+x5amYIaGAkCcVM9yfx6+Vx8zpXpG8/JcevD6TdizJvKgQvtI6CJ+hYfHF+sVwA9DKWPdVQI4+BESuh9uxLqHKj04i4WxiXtP5mukhFNFq9LRdkgO+RGy3W/MGvf1iXgWZ/CPW/f9UtqSkjUwMV/C54MAos0EBuFv0VlwxbXyTGR6LOka7i9QEwkLsdbgSqoNnfPlEN3ZWkRYmsdyOdIcWryqdnYgd6tjPB7Wnen65j04uHztcHAQXLAlwTIKXSCerNu9n9Jt30ZFo2VYnURPc2FpByDxkC9G+IufHPlntRjdmNdiDvmVzRijvUflNYDVaX9fs/l1t4q1eK9kphkAShYZjtKCJhs0n0HPN6zjhauvDN9CPQzcE+x9gSCCFrPYPy0pMr2EFGvQ7MlX296IxKjI+zsfqHDQKPwvdwCMcfyfi8+gIuhppRUp1l3LmMi34AsYKbDKtz9QqbCmtYeK185S6JwxP2CYlOKyhrfqzZwi0XR5pPXkR8RrR3Uk2yx7JP+ujZN+Xze3Uuhy1MXn05K+5UXh1oYQU0Aqt1JEjips+EhLqTV9fGHWKfVkGbu78vPKln0PDCnZxhLwaK3OpZAQvtTxHRM7VlIkWy+WGDlGGE+FOR9zBqFvaqvVvKr59TKKqnnHdCG/ivOh53+JvcHaBb0Xg=
  app: infinite-river-96832
  on:
    repo: jangusff/node-shopping-list-integration-tests
